version: 2
jobs:
  build:
    working_directory: /app
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t gps-test .
      - run:
          name: Run Tests
          command: docker run --name gps -d gps-test:1.0.0 node_modules/.bin/_mocha
