version: 2
jobs:
  build:
    working_directory: ~/app
    machine: true
    steps:
      - checkout
      - run:
          name: Run Tests
          environment:
            TEST_REPORT_DIR: ~/app/test-results
            MOCHA_FILE: $TEST_REPORT_DIR/result.xml
          command: |
            docker run -d --name redis redis:3.0.7
            mkdir -p $TEST_REPORT_DIR
            docker build -t dslagle/gps-test:$CIRCLE_SHA1 .
            docker run --link redis --rm dslagle/gps-test:$CIRCLE_SHA1 node_modules/.bin/_mocha --reporter mocha-junit-reporter
      - run:
          name: Push to Docker Hub
          environment:
            DOCKER_EMAIL: slagle.derek@gmail.com
            DOCKER_USER: dslagle
          command: |
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push dslagle/gps-test:$CIRCLE_SHA1
            docker logout
      - run:
          name: Deploy to AWS
          command: |
            aws configure set default.region us-east-1
            aws configure set default.output json
