version: 2
jobs:
  build:
    working_directory: ~/app
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: {{ checksum "Dockerfile" }}-{{checksum "package.json"}}
      - run:
          name: Build Docker Image
          command: docker build -t gps-test .
      - save_cache:
          key: {{ checksum "Dockerfile" }}-{{checksum "package.json"}}
      - run:
          name: Run Tests
          command: docker run --name gps gps-test node_modules/.bin/_mocha
