version: 2
jobs:
  build:
    working_directory: ~/app
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t gps-test .
      - run:
          name: Run Tests
          command: mkdir -p $CIRCLE_TEST_REPORTS/mocha && docker run --name gps gps-test node_modules/.bin/_mocha --reporter mocha-junit-reporter --reporter-options mochaFile=$CIRCLE_TEST_REPORTS/mocha/results.xml
