version: 2
jobs:
  build:
    working_directory: ~/app
    machine: true
    steps:
      - checkout
      - run:
          name: Run Tests
          environment:
            TEST_REPORT_DIR: ~/app/test-results
            MOCHA_FILE: $TEST_REPORT_DIR/result.xml
          command: |
            mkdir -p $TEST_REPORT_DIR
            DOCKER_IMAGE_TAG=$CIRCLE_SHA1 docker-compose -f docker-compose.test.yml up -d
      - run:
          name: Push to Docker Hub
          environment:
            DOCKER_EMAIL: slagle.derek@gmail.com
            DOCKER_USER: dslagle
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push dslagle/gps-test:$CIRCLE_SHA1
            docker logout
      - run:
          name: Deploy to AWS
          environment:
            DOCKER_IMAGE_TAG: $CIRCLE_SHA1
          command: |
            sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
            sudo chmod +x /usr/local/bin/ecs-cli
            ecs-cli configure --region us-east-1
            ecs-cli compose -f docker-compose.prod.yml -p frsd up
