version: "2"
services:
  api:
    build: .
    image: dslagle/gps-test:$DOCKER_IMAGE_TAG
    links:
      - "redis"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: node_modules/.bin/_mocha
  redis:
    image: redis:3.0.7
