version: "3"
services:
  api:
    build: .
    image: dslagle/gps-test:$DOCKER_IMAGE_TAG
    links:
      - "redis"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8080:8080
  redis:
    image: redis:3.0.7
