version: "2"
services:
  api:
    build: .
    image: dslagle/gps-test:$DOCKER_IMAGE_TAG
    links:
      - "redis"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MOCHA_FILE=$MOCHA_FILE
    ports:
      - 8080:8080
    command: node_modules/.bin/_mocha --reporter mocha-junit-reporter
  redis:
    image: redis:3.0.7
