version: "3"
services:
  rabbit1:
    image: rabbitmq:3.6.9
    hostname: rabbit1
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq_secret_key
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - frsdnet-v2

  rabbit2:
    image: dslagle/my-rabbit
    hostname: rabbit2
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq_secret_key
    networks:
      - frsdnet-v2

networks:
  frsdnet-v2:
    driver: overlay