version: "3"
services:
  rabbit1:
    image: rabbitmq:3.6.9
    hostname: rabbit1
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbit_secret
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - frsdnet-v2

  rabbit2:
    image: dslagle/my-rabbit:2.0.0
    hostname: rabbit2
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbit_secret
      - JOIN_NODE=rabbit@rabbit1
    networks:
      - frsdnet-v2

networks:
  frsdnet-v2:
    driver: overlay